%% Program for carrying out targeting of different Fresh Water sources.
function FW_f = trgt(N,Ind,FWC)
FWC = sort(FWC,'ascend');
FW_f = zeros(length(Ind),1); % Preallocating Freshwater Source Values. The number of sources will be equal to the number of Freshwater Conc. available.
[~, ~, ~, ~, IFWD] = wca(N,Ind,FW_f,FWC); % Need only Interval fresh water demand because the nature of these values (positive or negative) will detemine the fresh water deficit in the concerned interval.
Ind = sort(Ind,'ascend'); % Ind will already be in ascending order but we are still doing sorting as a preventive measure for errors not thought of till now. This vector is generated by 'imnor' where concentrations are already arranged in the ascending order by the program.
if min(IFWD) >= 0
    fprintf('Threshold Case: No Fresh Water Required.\n');
    return;
    % The threshold concentration will be...
end
if length(Ind) > 1 % If there are more than one FW concentrations, then FW targets will be be calculated for each of them.
    for i = 1:length(Ind)-1
        a = Ind(i)+1;
        b = Ind(i+1);
        if min(IFWD(a:b)) < 0 % If the min value is >= 0, then that particular FW source will remain zero only.
            FW_f(i) = -1*min(IFWD(a:b));
        end
        [~, ~, ~, ~, IFWD] = wca(N,Ind,FW_f,FWC);
    end
    a = b + 1;
    b = N(end,1);
    if min(IFWD(a:b)) < 0
        FW_f(end) = -1*min(IFWD(a:b));
    end        
else % Simple single targeting for only one FW source, whether impure or pure.
    a = Ind(1) + 1;
    b = N(end,1);
    if min(IFWD(a:b)) < 0
        FW_f = -1*min(IFWD(a:b));
    end
end
end